services:
  contacts:
    build: .
    restart: on-failure
    depends_on:
      - mongo
    ports:
      - "8080:8080"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - "./data:/data/db"